In [10]:
import pandas as pd
import numpy as np

In [11]:
# np.random.seed(42) # Set random seed for reproducibility
# n_rows=1000 # Generate 1000 rows with 4 columns

In [14]:
np.random.seed(42)

n_rows = 1000
data = {
    'color': np.random.choice(['red', 'blue', 'green'], n_rows),
    'size': np.random.choice(['small', 'medium', 'large'], n_rows),
    'material': np.random.choice(['plastic', 'metal', 'wood'], n_rows),
    'price': np.random.randint(10, 500, n_rows)
}
df = pd.DataFrame(data)

# Display first few rows
print(df.head())
print(f"\nDataset shape: {df.shape}")

   color   size material  price
0  green  large    metal    423
1    red  large  plastic    351
2  green  large  plastic    229
3  green  large     wood    400
4    red  small  plastic    172

Dataset shape: (1000, 4)

In [15]:
pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in c:\users\mural\anaconda3\lib\site-packages (from category_encoders) (2.3.5)
Requirement already satisfied: pandas>=1.0.5 in c:\users\mural\anaconda3\lib\site-packages (from category_encoders) (2.3.3)
Requirement already satisfied: patsy>=0.5.1 in c:\users\mural\anaconda3\lib\site-packages (from category_encoders) (1.0.1)
Requirement already satisfied: scikit-learn>=1.6.0 in c:\users\mural\anaconda3\lib\site-packages (from category_encoders) (1.7.2)
Requirement already satisfied: scipy>=1.0.0 in c:\users\mural\anaconda3\lib\site-packages (from category_encoders) (1.16.3)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\mural\anaconda3\lib\site-packages (from category_encoders) (0.14.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mural\anaconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mural\anaconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mural\anaconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\mural\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\mural\anaconda3\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\mural\anaconda3\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (3.5.0)
Requirement already satisfied: packaging>=21.3 in c:\users\mural\anaconda3\lib\site-packages (from statsmodels>=0.9.0->category_encoders) (25.0)
Downloading category_encoders-2.9.0-py3-none-any.whl (85 kB)
Installing collected packages: category_encoders
Successfully installed category_encoders-2.9.0
Note: you may need to restart the kernel to use updated packages.

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder
from category_encoders import TargetEncoder

In [17]:
x=df[['color','size','material']]
y=df['price']

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [19]:
label_encoder=LabelEncoder()

In [20]:
# while doing label_encoder.fit_transform we cannot pass multiple columns

In [21]:
updated_xtrain=label_encoder.fit_transform(x_train['color'])
updated_xtrain

array([1, 0, 0, 2, 1, 1, 2, 1, 0, 1, 0, 1, 0, 0, 0, 2, 0, 1, 1, 2, 0, 1,
       2, 0, 2, 1, 1, 1, 1, 2, 2, 0, 0, 2, 0, 1, 2, 2, 2, 1, 1, 0, 2, 1,
       2, 0, 1, 1, 2, 2, 0, 1, 0, 0, 1, 1, 1, 1, 0, 2, 2, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 0, 2, 0, 1, 0, 2, 2, 2, 2,
       1, 1, 2, 2, 0, 1, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 2, 1, 2,
       2, 1, 1, 1, 1, 0, 1, 1, 2, 1, 0, 2, 2, 2, 2, 2, 1, 0, 0, 0, 2, 1,
       2, 0, 1, 0, 1, 0, 2, 1, 0, 0, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 0, 2,
       2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 0, 1, 1, 2, 2, 0, 0, 0, 1, 0, 1, 1,
       2, 0, 1, 1, 1, 1, 2, 2, 2, 0, 0, 2, 0, 2, 2, 1, 1, 2, 1, 1, 1, 0,
       0, 1, 2, 0, 0, 0, 0, 2, 0, 2, 2, 1, 1, 1, 2, 0, 1, 0, 0, 0, 2, 1,
       0, 0, 0, 1, 0, 1, 2, 2, 0, 2, 1, 0, 2, 0, 2, 2, 0, 0, 1, 2, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 2, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 2, 0, 2, 0, 0, 2, 1, 2, 2, 2, 0, 1, 2, 1, 0, 2, 1, 0, 1, 2,
       1, 1, 2, 2, 2, 2, 2, 1, 0, 2, 0, 0, 1, 2, 2, 0, 0, 2, 2, 2, 2, 0,
       0, 2, 2, 0, 2, 2, 1, 1, 0, 2, 2, 0, 2, 2, 1, 2, 1, 2, 0, 0, 2, 1,
       1, 0, 0, 2, 1, 0, 1, 0, 1, 0, 0, 0, 0, 2, 1, 1, 1, 1, 1, 1, 2, 2,
       1, 2, 1, 2, 1, 0, 0, 1, 0, 2, 1, 1, 1, 2, 1, 2, 0, 1, 2, 1, 2, 0,
       2, 2, 0, 1, 1, 0, 2, 0, 0, 2, 2, 0, 0, 2, 2, 2, 1, 0, 1, 0, 0, 2,
       0, 2, 2, 2, 0, 2, 0, 1, 1, 2, 2, 0, 1, 0, 2, 2, 1, 2, 2, 2, 1, 1,
       2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 0, 2, 2, 2, 0, 2, 0, 0, 2, 0, 2, 2,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 2, 1, 2, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 2, 2, 0, 1, 1, 2, 2, 0, 2, 2, 1, 1, 1, 1, 0, 2, 1,
       0, 1, 0, 2, 2, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 0, 2, 2, 0, 2, 2, 1,
       1, 1, 0, 1, 0, 0, 2, 2, 0, 1, 1, 2, 1, 0, 2, 1, 0, 2, 2, 0, 0, 2,
       2, 1, 1, 2, 1, 1, 0, 1, 0, 0, 2, 1, 1, 0, 2, 0, 2, 2, 2, 1, 1, 1,
       2, 1, 2, 1, 1, 2, 1, 1, 1, 0, 2, 2, 1, 1, 0, 1, 0, 2, 1, 0, 2, 2,
       0, 0, 2, 0, 1, 0, 1, 2, 0, 1, 1, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 0,
       2, 1, 0, 0, 1, 1, 2, 2, 0, 2, 0, 1, 2, 1, 2, 0, 0, 0, 1, 2, 2, 2,
       1, 0, 2, 1, 2, 1, 0, 1, 2, 2, 2, 0, 2, 0, 1, 1, 2, 1, 2, 2, 0, 0,
       2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 1, 2, 0, 2, 2, 2, 1, 1, 1, 1, 2, 2,
       2, 0, 1, 2, 1, 0, 0, 1, 0, 0, 2, 1, 0, 2, 0, 1, 0, 0, 0, 1, 2, 2,
       1, 1, 0, 0, 1, 0, 2, 0, 2, 1, 2, 0, 1, 1, 2, 2, 1, 0, 2, 1, 2, 0,
       1, 0, 0, 0, 2, 2, 2, 2, 1, 0, 2, 2, 1, 0, 0, 1, 1, 1, 0, 0, 2, 2,
       0, 2, 0, 0, 1, 2, 1, 2, 1, 0, 2, 0, 0, 0, 0, 0, 2, 1, 2, 1, 2, 0,
       0, 2, 1, 2, 1, 1, 0, 0, 2, 0, 1, 1, 0, 1, 0, 0, 1, 2, 0, 2, 1, 1,
       0, 0, 0, 1, 0, 0, 2, 1, 1, 2, 1, 0, 0, 2, 1, 2, 0, 2, 0, 2, 1, 1,
       2, 1, 0, 2, 2, 0, 0, 1])

In [22]:
updated_xtest=label_encoder.fit_transform(x_test['color'])
updated_xtest

array([2, 2, 0, 1, 0, 2, 1, 2, 2, 0, 0, 0, 2, 0, 1, 2, 1, 2, 2, 0, 1, 1,
       1, 0, 2, 0, 1, 2, 0, 1, 2, 2, 0, 1, 0, 0, 2, 2, 2, 1, 2, 2, 1, 2,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 0, 1, 1, 1, 2, 0, 0, 1, 2, 2, 1,
       2, 2, 1, 2, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 2, 0, 0, 2, 1, 0,
       2, 0, 2, 2, 0, 2, 0, 1, 2, 0, 0, 1, 0, 2, 0, 0, 2, 1, 2, 2, 2, 2,
       0, 0, 2, 1, 1, 2, 2, 0, 2, 2, 2, 1, 0, 2, 0, 2, 2, 2, 1, 0, 2, 2,
       0, 0, 2, 1, 2, 0, 2, 0, 2, 1, 1, 1, 0, 2, 2, 2, 0, 1, 2, 2, 0, 1,
       0, 2, 2, 2, 0, 0, 2, 2, 1, 1, 1, 2, 0, 2, 1, 2, 1, 1, 1, 0, 0, 0,
       2, 2, 0, 2, 0, 2, 2, 1, 0, 1, 1, 0, 0, 0, 2, 0, 0, 2, 2, 1, 2, 2,
       1, 1])

In [23]:
# LabelEncoder can't handle unknown values
# label_encoder.transform(['brown']) cannot be done as it can't handle unknown values (unseen data)

# OneHotEncoder()

In [ ]:
onehot_encoder=OneHotEncoder(sparse_output=False)
# By default sparse_output is True
# sparse_output is used to conver into array by giving sparse_output as False

# or we can do 

# values=values.toarray() to convert into array

In [25]:
values=onehot_encoder.fit_transform(x_train)
values

array([[0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]], shape=(800, 9))

In [26]:
# onehot_encoder.transform(xtest[['color','size']])
# we need to pass all the feature columns otherwise it raise ValueError

In [27]:
onehot_encoder.transform(x_test)

array([[0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]], shape=(200, 9))

In [28]:
# onehot_encoder.transform([['red','large'],['blue','small']])
# ValueError: X has 2 features, but OneHotEncoder is expecting 3 features as input

In [29]:
onehot_encoder.transform([['red','large','plastic'],['blue','small','wood']])

c:\Users\mural\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 1., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.]])

In [30]:
# onehot_encoder.transform([['red1','large2','plastic'],['blue','small2','wood']]) 
# ValueError: Found unknown categories ['red1'] in column 0 during transform

In [31]:
onehot_encoder=OneHotEncoder(sparse_output=False,handle_unknown='ignore') # Default handle_unknow is error
values=onehot_encoder.fit_transform(x_train)
onehot_encoder.transform([['red1','large3','plastic'],['blue','small','wood']])

c:\Users\mural\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.]])

In [32]:
# red1 and large3 is not in the data so it gives 0

In [33]:
onehot_encoder.get_feature_names_out()

array(['color_blue', 'color_green', 'color_red', 'size_large',
       'size_medium', 'size_small', 'material_metal', 'material_plastic',
       'material_wood'], dtype=object)

# Ordinal Encoder()

In [34]:
ordinal_encoder=OrdinalEncoder()

In [35]:
updated_xtrain=ordinal_encoder.fit_transform(x_train)
updated_xtrain

array([[1., 2., 2.],
       [0., 1., 0.],
       [0., 2., 2.],
       ...,
       [0., 0., 1.],
       [0., 2., 1.],
       [1., 2., 1.]], shape=(800, 3))

In [36]:
# updated_xtest=ordinal_encoder.transform(xtest[['color']])
# It excepts 2D and also all the feature column names which are passed

In [37]:
updated_xtest=ordinal_encoder.transform(x_test)
updated_xtest

array([[2., 2., 0.],
       [2., 2., 0.],
       [0., 2., 0.],
       [1., 2., 1.],
       [0., 1., 0.],
       [2., 0., 1.],
       [1., 0., 1.],
       [2., 2., 1.],
       [2., 0., 0.],
       [0., 2., 0.],
       [0., 2., 0.],
       [0., 0., 0.],
       [2., 0., 1.],
       [0., 1., 2.],
       [1., 2., 0.],
       [2., 0., 0.],
       [1., 1., 2.],
       [2., 0., 1.],
       [2., 0., 2.],
       [0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 2., 1.],
       [0., 1., 1.],
       [2., 1., 1.],
       [0., 1., 2.],
       [1., 0., 0.],
       [2., 2., 0.],
       [0., 2., 0.],
       [1., 1., 1.],
       [2., 1., 0.],
       [2., 0., 2.],
       [0., 2., 0.],
       [1., 2., 0.],
       [0., 1., 0.],
       [0., 0., 2.],
       [2., 2., 2.],
       [2., 1., 1.],
       [2., 1., 0.],
       [1., 0., 0.],
       [2., 2., 2.],
       [2., 1., 2.],
       [1., 0., 0.],
       [2., 0., 1.],
       [0., 0., 1.],
       [1., 0., 2.],
       [1., 0., 2.],
       [1., 2., 2.],
       [1., 1., 0.],
       [1., 0., 1.],
       [1., 0., 2.],
       [0., 0., 2.],
       [0., 2., 0.],
       [2., 2., 2.],
       [0., 2., 2.],
       [0., 2., 0.],
       [1., 1., 2.],
       [1., 1., 2.],
       [1., 0., 0.],
       [2., 0., 1.],
       [0., 1., 2.],
       [0., 0., 0.],
       [1., 2., 1.],
       [2., 1., 2.],
       [2., 2., 2.],
       [1., 2., 1.],
       [2., 1., 0.],
       [2., 2., 1.],
       [1., 1., 1.],
       [2., 0., 0.],
       [1., 0., 1.],
       [1., 2., 2.],
       [1., 2., 2.],
       [0., 2., 0.],
       [1., 1., 1.],
       [1., 1., 2.],
       [0., 0., 1.],
       [1., 0., 1.],
       [0., 2., 1.],
       [1., 1., 2.],
       [0., 1., 1.],
       [0., 2., 2.],
       [2., 0., 0.],
       [0., 2., 1.],
       [0., 2., 1.],
       [2., 1., 0.],
       [1., 0., 0.],
       [0., 2., 2.],
       [2., 2., 0.],
       [0., 0., 2.],
       [2., 0., 2.],
       [2., 0., 1.],
       [0., 0., 0.],
       [2., 0., 2.],
       [0., 1., 0.],
       [1., 1., 0.],
       [2., 0., 2.],
       [0., 2., 1.],
       [0., 0., 0.],
       [1., 1., 2.],
       [0., 1., 2.],
       [2., 0., 0.],
       [0., 1., 1.],
       [0., 0., 0.],
       [2., 2., 2.],
       [1., 1., 1.],
       [2., 0., 1.],
       [2., 0., 0.],
       [2., 0., 2.],
       [2., 2., 1.],
       [0., 0., 2.],
       [0., 0., 2.],
       [2., 0., 2.],
       [1., 2., 1.],
       [1., 2., 0.],
       [2., 0., 0.],
       [2., 1., 2.],
       [0., 0., 1.],
       [2., 2., 2.],
       [2., 1., 1.],
       [2., 1., 1.],
       [1., 0., 1.],
       [0., 0., 0.],
       [2., 2., 0.],
       [0., 0., 0.],
       [2., 0., 0.],
       [2., 0., 0.],
       [2., 0., 2.],
       [1., 0., 2.],
       [0., 2., 2.],
       [2., 2., 0.],
       [2., 1., 2.],
       [0., 2., 2.],
       [0., 2., 2.],
       [2., 1., 1.],
       [1., 2., 1.],
       [2., 1., 2.],
       [0., 0., 1.],
       [2., 1., 2.],
       [0., 0., 0.],
       [2., 1., 0.],
       [1., 1., 1.],
       [1., 2., 2.],
       [1., 2., 0.],
       [0., 0., 2.],
       [2., 0., 0.],
       [2., 0., 2.],
       [2., 0., 0.],
       [0., 0., 2.],
       [1., 0., 2.],
       [2., 2., 1.],
       [2., 2., 2.],
       [0., 0., 1.],
       [1., 2., 2.],
       [0., 1., 2.],
       [2., 1., 2.],
       [2., 1., 2.],
       [2., 0., 2.],
       [0., 0., 0.],
       [0., 2., 0.],
       [2., 1., 1.],
       [2., 1., 2.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 1., 1.],
       [2., 0., 1.],
       [0., 1., 1.],
       [2., 2., 0.],
       [1., 1., 0.],
       [2., 1., 2.],
       [1., 1., 2.],
       [1., 2., 1.],
       [1., 2., 1.],
       [0., 0., 1.],
       [0., 0., 2.],
       [0., 1., 0.],
       [2., 2., 2.],
       [2., 1., 0.],
       [0., 1., 0.],
       [2., 1., 1.],
       [0., 0., 1.],
       [2., 2., 0.],
       [2., 2., 2.],
       [1., 2., 0.],
       [0., 0., 0.],
       [1., 2., 1.],
       [1., 1., 0.],
       [0., 0., 0.],
       [0., 2., 0.],
       [0., 1., 0.],
       [2., 1., 0.],
       [0., 1., 2.],
       [0., 0., 2.],
       [2., 2., 2.],
       [2., 2., 1.],
       [1., 2., 0.],
       [2., 0., 0.],
       [2., 2., 0.],
       [1., 2., 1.],
       [1., 1., 1.]])

In [38]:
ordinal_encoder.get_feature_names_out()

array(['color', 'size', 'material'], dtype=object)

In [40]:
# To handle unknown values we need to give "use_encoded_values" and unknown_values =1

In [43]:
ordinal_encoder=OrdinalEncoder(handle_unknown='use_encoded_value',unknown_value=-1)

updated_xtrain=ordinal_encoder.fit_transform(x_train)
updated_xtest=ordinal_encoder.transform(x_test)

values=ordinal_encoder.transform([['red1','large3','plastic'],['blue','small','wood']])
values

c:\Users\mural\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[-1., -1.,  1.],
       [ 0.,  2.,  2.]])

In [44]:
# red1 and large3 are not in the data so ordinal encoder has assigned -1 to it

In [46]:
values=pd.DataFrame([['red1','large','wood'],['blue','small','fiber']],columns=['color','size','material'])
updated_values=ordinal_encoder.transform(values)
updated_values

# This doesnot gives warning

array([[-1.,  0.,  2.],
       [ 0.,  2., -1.]])

In [47]:
x_train['color'].unique()

array(['green', 'blue', 'red'], dtype=object)

In [48]:
df

     color    size material  price
0    green   large    metal    423
1      red   large  plastic    351
2    green   large  plastic    229
3    green   large     wood    400
4      red   small  plastic    172
..     ...     ...      ...    ...
995   blue   small     wood    286
996   blue   large  plastic    473
997  green  medium  plastic    213
998  green   large    metal    203
999    red   large    metal    178

[1000 rows x 4 columns]

# With Order

In [49]:
ordinal_encoder=OrdinalEncoder(categories=[['red','green','blue'],['small','medium','large'],['wood','metal','plastic']],handle_unknown='use_encoded_value',unknown_value=-1)
updated_xtrain=ordinal_encoder.fit_transform(x_train)
updated_xtrain

array([[1., 0., 0.],
       [2., 1., 1.],
       [2., 0., 0.],
       ...,
       [2., 2., 2.],
       [2., 0., 2.],
       [1., 0., 2.]], shape=(800, 3))

In [52]:
updated_xtrain=ordinal_encoder.fit_transform(x_train)
updated_xtest

array([[2., 2., 0.],
       [2., 2., 0.],
       [0., 2., 0.],
       [1., 2., 1.],
       [0., 1., 0.],
       [2., 0., 1.],
       [1., 0., 1.],
       [2., 2., 1.],
       [2., 0., 0.],
       [0., 2., 0.],
       [0., 2., 0.],
       [0., 0., 0.],
       [2., 0., 1.],
       [0., 1., 2.],
       [1., 2., 0.],
       [2., 0., 0.],
       [1., 1., 2.],
       [2., 0., 1.],
       [2., 0., 2.],
       [0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 2., 1.],
       [0., 1., 1.],
       [2., 1., 1.],
       [0., 1., 2.],
       [1., 0., 0.],
       [2., 2., 0.],
       [0., 2., 0.],
       [1., 1., 1.],
       [2., 1., 0.],
       [2., 0., 2.],
       [0., 2., 0.],
       [1., 2., 0.],
       [0., 1., 0.],
       [0., 0., 2.],
       [2., 2., 2.],
       [2., 1., 1.],
       [2., 1., 0.],
       [1., 0., 0.],
       [2., 2., 2.],
       [2., 1., 2.],
       [1., 0., 0.],
       [2., 0., 1.],
       [0., 0., 1.],
       [1., 0., 2.],
       [1., 0., 2.],
       [1., 2., 2.],
       [1., 1., 0.],
       [1., 0., 1.],
       [1., 0., 2.],
       [0., 0., 2.],
       [0., 2., 0.],
       [2., 2., 2.],
       [0., 2., 2.],
       [0., 2., 0.],
       [1., 1., 2.],
       [1., 1., 2.],
       [1., 0., 0.],
       [2., 0., 1.],
       [0., 1., 2.],
       [0., 0., 0.],
       [1., 2., 1.],
       [2., 1., 2.],
       [2., 2., 2.],
       [1., 2., 1.],
       [2., 1., 0.],
       [2., 2., 1.],
       [1., 1., 1.],
       [2., 0., 0.],
       [1., 0., 1.],
       [1., 2., 2.],
       [1., 2., 2.],
       [0., 2., 0.],
       [1., 1., 1.],
       [1., 1., 2.],
       [0., 0., 1.],
       [1., 0., 1.],
       [0., 2., 1.],
       [1., 1., 2.],
       [0., 1., 1.],
       [0., 2., 2.],
       [2., 0., 0.],
       [0., 2., 1.],
       [0., 2., 1.],
       [2., 1., 0.],
       [1., 0., 0.],
       [0., 2., 2.],
       [2., 2., 0.],
       [0., 0., 2.],
       [2., 0., 2.],
       [2., 0., 1.],
       [0., 0., 0.],
       [2., 0., 2.],
       [0., 1., 0.],
       [1., 1., 0.],
       [2., 0., 2.],
       [0., 2., 1.],
       [0., 0., 0.],
       [1., 1., 2.],
       [0., 1., 2.],
       [2., 0., 0.],
       [0., 1., 1.],
       [0., 0., 0.],
       [2., 2., 2.],
       [1., 1., 1.],
       [2., 0., 1.],
       [2., 0., 0.],
       [2., 0., 2.],
       [2., 2., 1.],
       [0., 0., 2.],
       [0., 0., 2.],
       [2., 0., 2.],
       [1., 2., 1.],
       [1., 2., 0.],
       [2., 0., 0.],
       [2., 1., 2.],
       [0., 0., 1.],
       [2., 2., 2.],
       [2., 1., 1.],
       [2., 1., 1.],
       [1., 0., 1.],
       [0., 0., 0.],
       [2., 2., 0.],
       [0., 0., 0.],
       [2., 0., 0.],
       [2., 0., 0.],
       [2., 0., 2.],
       [1., 0., 2.],
       [0., 2., 2.],
       [2., 2., 0.],
       [2., 1., 2.],
       [0., 2., 2.],
       [0., 2., 2.],
       [2., 1., 1.],
       [1., 2., 1.],
       [2., 1., 2.],
       [0., 0., 1.],
       [2., 1., 2.],
       [0., 0., 0.],
       [2., 1., 0.],
       [1., 1., 1.],
       [1., 2., 2.],
       [1., 2., 0.],
       [0., 0., 2.],
       [2., 0., 0.],
       [2., 0., 2.],
       [2., 0., 0.],
       [0., 0., 2.],
       [1., 0., 2.],
       [2., 2., 1.],
       [2., 2., 2.],
       [0., 0., 1.],
       [1., 2., 2.],
       [0., 1., 2.],
       [2., 1., 2.],
       [2., 1., 2.],
       [2., 0., 2.],
       [0., 0., 0.],
       [0., 2., 0.],
       [2., 1., 1.],
       [2., 1., 2.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 1., 1.],
       [2., 0., 1.],
       [0., 1., 1.],
       [2., 2., 0.],
       [1., 1., 0.],
       [2., 1., 2.],
       [1., 1., 2.],
       [1., 2., 1.],
       [1., 2., 1.],
       [0., 0., 1.],
       [0., 0., 2.],
       [0., 1., 0.],
       [2., 2., 2.],
       [2., 1., 0.],
       [0., 1., 0.],
       [2., 1., 1.],
       [0., 0., 1.],
       [2., 2., 0.],
       [2., 2., 2.],
       [1., 2., 0.],
       [0., 0., 0.],
       [1., 2., 1.],
       [1., 1., 0.],
       [0., 0., 0.],
       [0., 2., 0.],
       [0., 1., 0.],
       [2., 1., 0.],
       [0., 1., 2.],
       [0., 0., 2.],
       [2., 2., 2.],
       [2., 2., 1.],
       [1., 2., 0.],
       [2., 0., 0.],
       [2., 2., 0.],
       [1., 2., 1.],
       [1., 1., 1.]])

In [53]:
ordinal_encoder.transform([['red','medium','wood']])

c:\Users\mural\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0., 1., 0.]])

# Target Encoder

In [55]:
target_encoder=TargetEncoder(cols=['color'],handle_unknown='value')
updated_xtrain=target_encoder.fit_transform(x_train,y_train)
updated_xtrain

          color    size material
29   253.164751   small     wood
535  256.408397  medium    metal
695  256.408397   small     wood
557  263.678700   small  plastic
836  253.164751   large  plastic
..          ...     ...      ...
106  263.678700   large  plastic
270  263.678700   small  plastic
860  256.408397   large  plastic
435  256.408397   small  plastic
102  253.164751   small  plastic

[800 rows x 3 columns]

In [56]:
updated_xtest=target_encoder.transform(x_test)
updated_xtest

          color    size material
521  263.678700   small    metal
737  263.678700   small    metal
740  256.408397   small    metal
660  253.164751   small  plastic
411  256.408397  medium    metal
..          ...     ...      ...
408  253.164751   small    metal
332  263.678700   large    metal
208  263.678700   small    metal
613  253.164751   small  plastic
78   253.164751  medium  plastic

[200 rows x 3 columns]

In [57]:
new_input=pd.DataFrame({
    'color':['red1'],
    'size':['small'],
    'material':['metal']
})
updated_input=target_encoder.transform(new_input)
updated_input

      color   size material
0  257.8675  small    metal