In [1]:
import pandas as pd

In [2]:
pd.Series([1,2,3,4,5],index=['A','B','C','D','E'])

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [3]:
pd.Series({1:100,2:200,3:300})

1    100
2    200
3    300
dtype: int64

# Must give index when giving non scalar value

In [4]:
pd.DataFrame({1:"One",2:"Two",3:"Three"},index=[1,2,3])

     1    2      3
1  One  Two  Three
2  One  Two  Three
3  One  Two  Three

# Dictionary Creation In Dataframe

In [5]:
data={"Age":[25,29,30], "Sal":[10000,20000,30000],"Exp":[2,4,7]}
pd.DataFrame(data)

   Age    Sal  Exp
0   25  10000    2
1   29  20000    4
2   30  30000    7

In [6]:
# data={"Age":[23,26,29], "Sal":[10000,20000]} #raises ValueError as the number values dont match
# pandas.DataFrame(data)

In [7]:
df=pd.read_csv("D:\machine_learning\datasets\studentperformance.csv")

In [11]:
# df.head() # .head() by default it gives 5 records
df.head(2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [12]:
df.tail() # last 5 records

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [13]:
df.dtypes # Gives all type of datatypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [14]:
df.columns # Gives all columns name

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [ ]:
df['gender']  # Single column

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [16]:
df[['gender','lunch']]  # Multipke columns [[]]

     gender         lunch
0    female      standard
1    female      standard
2    female      standard
3      male  free/reduced
4      male      standard
..      ...           ...
995  female      standard
996    male  free/reduced
997  female  free/reduced
998  female      standard
999  female  free/reduced

[1000 rows x 2 columns]