In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('D:\machine_learning\datasets\studentperformance.csv')

In [3]:
df.iloc[0]

gender                                    female
race/ethnicity                           group B
parental level of education    bachelor's degree
lunch                                   standard
test preparation course                     none
math score                                    72
reading score                                 72
writing score                                 74
Name: 0, dtype: object

In [ ]:
df.iloc[0,1] # Row index,Column index

'group B'

In [5]:
df.iloc[0,3]

'standard'

In [6]:
df.iloc[2]

gender                                  female
race/ethnicity                         group B
parental level of education    master's degree
lunch                                 standard
test preparation course                   none
math score                                  90
reading score                               95
writing score                               93
Name: 2, dtype: object

In [ ]:
df.iloc[[0,3]] # Returns only the rows not column as column is not mentioned

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
3,male,group A,associate's degree,free/reduced,none,47,57,44

In [10]:
df.iloc[[0,3],[1,2]] # 0 and 3 row and 1 and 2 column

  race/ethnicity parental level of education
0        group B           bachelor's degree
3        group A          associate's degree

In [11]:
df.iloc[1:3] # 1 and 2 rows , All columns

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93

In [12]:
df.iloc[:,:] # All rows and All columns

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [13]:
df.iloc[:,0:3] # All rows and 0,1,2 columns

     gender race/ethnicity parental level of education
0    female        group B           bachelor's degree
1    female        group C                some college
2    female        group B             master's degree
3      male        group A          associate's degree
4      male        group C                some college
..      ...            ...                         ...
995  female        group E             master's degree
996    male        group C                 high school
997  female        group C                 high school
998  female        group D                some college
999  female        group D                some college

[1000 rows x 3 columns]

In [15]:
#df.iloc[:,['gender']] # IndexError: .iloc requires numeric indexers, got ['gender']

In [16]:
df.iloc[-1] # last row

gender                               female
race/ethnicity                      group D
parental level of education    some college
lunch                          free/reduced
test preparation course                none
math score                               77
reading score                            86
writing score                            86
Name: 999, dtype: object

# LOC

In [19]:
df.loc[0]

gender                                    female
race/ethnicity                           group B
parental level of education    bachelor's degree
lunch                                   standard
test preparation course                     none
math score                                    72
reading score                                 72
writing score                                 74
Name: 0, dtype: object

In [ ]:
df.loc[3,'gender'] # Can add column name

'male'

In [23]:
# df.loc[0,3] # gives error if used integer in column value
# KeyError: 3

In [24]:
df.loc[:,:]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [25]:
df.loc[1:3,'gender'] # in loc the end value is included

1    female
2    female
3      male
Name: gender, dtype: object

In [27]:
df.loc[0:,'gender':'lunch']# same as iloc, all rows but only include columns gender to lunch

     gender race/ethnicity parental level of education         lunch
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

[1000 rows x 4 columns]

In [28]:
df.loc[:5,['gender']] # as dataframe beacuse 2D

   gender
0  female
1  female
2  female
3    male
4    male
5  female

In [29]:
df.loc[0:4,['gender','lunch']] # selects mentioned rows and the two distinct columns mentioned

   gender         lunch
0  female      standard
1  female      standard
2  female      standard
3    male  free/reduced
4    male      standard

In [30]:
df['gender']=='male' # returns the 1-D series

0      False
1      False
2      False
3       True
4       True
       ...
995    False
996     True
997    False
998    False
999    False
Name: gender, Length: 1000, dtype: bool

In [31]:
df[df['gender']=='male'] #returns the all the columns where gender contains male 2-D dataftrame

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
10,male,group C,associate's degree,standard,none,58,54,52
...,...,...,...,...,...,...,...,...
985,male,group A,high school,standard,none,57,51,54
987,male,group E,some high school,standard,completed,81,75,76
990,male,group E,high school,free/reduced,completed,86,81,75
994,male,group A,high school,standard,none,63,63,62
996,male,group C,high school,free/reduced,none,62,55,55