In [50]:
import pandas as pd

In [51]:
df=pd.read_csv('D:\machine_learning\datasets\googleplaystore.csv')

In [52]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [54]:
df.dtypes

App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [55]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [56]:
# df['Size']=df["Size"].str.replace('M','').str.replace('+','').str.replace('k','').str.replace(',','')

# df['Size']=df["Size"].replace({'Varies with device':None})

In [57]:
# df['Size'].astype(float)

In [58]:
# # Convert Size,installs,price to integer
def convert(value):
    value=value.replace('M','')
    value=value.replace('+','')
    value=value.replace('k','')
    value=value.replace(',','')
    if value=='Varies with device':
        value=None
    return value


# def changes(value):
#     if 'M' in value:
#         return value.removesuffix('M')
#     if value=='Varies with device':
#         return None
#     if "+" in value:
#         return value.removesuffix('+')
#     if "k" in value:
#         return value.removesuffix('k')
#     if ',' in value:
#         return value.replace(',','')

# Run All Once Again **

In [59]:
df['Size']=df['Size'].apply(convert)
df['Size']=df['Size'].astype(float)

# df['Size']=df['Size'].apply(changes)

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            9146 non-null   float64
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(2), object(11)
memory usage: 1.1+ MB

In [61]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [62]:
df['Installs']=df['Installs'].str.replace('+','').str.replace(',','')
df['Installs']=df['Installs'].replace({'Free':None})
df['Installs']=df['Installs'].astype(float)

In [63]:
df['Price']=df['Price'].str.replace('$','')
df['Price']=df['Price'].replace({'Everyone':None})
df['Price']=df['Price'].astype(float)

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            9146 non-null   float64
 5   Installs        10840 non-null  float64
 6   Type            10840 non-null  object
 7   Price           10840 non-null  float64
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(4), object(9)
memory usage: 1.1+ MB

# Assignment 2

In [65]:
# What are the Top 10frequent app categories
df['Category'].value_counts().head(10)

Category
FAMILY             1972
GAME               1144
TOOLS               843
MEDICAL             463
BUSINESS            460
PRODUCTIVITY        424
PERSONALIZATION     392
COMMUNICATION       387
SPORTS              384
LIFESTYLE           382
Name: count, dtype: int64

In [66]:
# Group by rating with mean
df.groupby('Category')['Rating'].mean()

Category
1.9                    19.000000
ART_AND_DESIGN          4.358065
AUTO_AND_VEHICLES       4.190411
BEAUTY                  4.278571
BOOKS_AND_REFERENCE     4.346067
BUSINESS                4.121452
COMICS                  4.155172
COMMUNICATION           4.158537
DATING                  3.970769
EDUCATION               4.389032
ENTERTAINMENT           4.126174
EVENTS                  4.435556
FAMILY                  4.192272
FINANCE                 4.131889
FOOD_AND_DRINK          4.166972
GAME                    4.286326
HEALTH_AND_FITNESS      4.277104
HOUSE_AND_HOME          4.197368
LIBRARIES_AND_DEMO      4.178462
LIFESTYLE               4.094904
MAPS_AND_NAVIGATION     4.051613
MEDICAL                 4.189143
NEWS_AND_MAGAZINES      4.132189
PARENTING               4.300000
PERSONALIZATION         4.335987
PHOTOGRAPHY             4.192114
PRODUCTIVITY            4.211396
SHOPPING                4.259664
SOCIAL                  4.255598
SPORTS                  4.223511
TOOLS                   4.047411
TRAVEL_AND_LOCAL        4.109292
VIDEO_PLAYERS           4.063750
WEATHER                 4.244000
Name: Rating, dtype: float64

In [67]:
df['Rating'].mean().max()

np.float64(4.193338315362443)

In [68]:
df.groupby('Category')['Rating'].agg({'mean','max'})

                      max       mean
Category
1.9                  19.0  19.000000
ART_AND_DESIGN        5.0   4.358065
AUTO_AND_VEHICLES     4.9   4.190411
BEAUTY                4.9   4.278571
BOOKS_AND_REFERENCE   5.0   4.346067
BUSINESS              5.0   4.121452
COMICS                5.0   4.155172
COMMUNICATION         5.0   4.158537
DATING                5.0   3.970769
EDUCATION             4.9   4.389032
ENTERTAINMENT         4.7   4.126174
EVENTS                5.0   4.435556
FAMILY                5.0   4.192272
FINANCE               5.0   4.131889
FOOD_AND_DRINK        5.0   4.166972
GAME                  5.0   4.286326
HEALTH_AND_FITNESS    5.0   4.277104
HOUSE_AND_HOME        4.8   4.197368
LIBRARIES_AND_DEMO    5.0   4.178462
LIFESTYLE             5.0   4.094904
MAPS_AND_NAVIGATION   4.9   4.051613
MEDICAL               5.0   4.189143
NEWS_AND_MAGAZINES    5.0   4.132189
PARENTING             5.0   4.300000
PERSONALIZATION       5.0   4.335987
PHOTOGRAPHY           5.0   4.192114
PRODUCTIVITY          5.0   4.211396
SHOPPING              5.0   4.259664
SOCIAL                5.0   4.255598
SPORTS                5.0   4.223511
TOOLS                 5.0   4.047411
TRAVEL_AND_LOCAL      5.0   4.109292
VIDEO_PLAYERS         4.9   4.063750
WEATHER               4.8   4.244000

In [69]:
df['Size'].mode()

0    11.0
Name: Size, dtype: float64

In [70]:
df['Type'].value_counts()

Type
Free    10039
Paid      800
0           1
Name: count, dtype: int64

In [72]:
df.groupby('Type')['Price'].mean()

Type
0             NaN
Free     0.000000
Paid    13.920837
Name: Price, dtype: float64

In [73]:
#Which category has the highest number of installs overall?
df.groupby('Category')['Installs'].sum()

Category
1.9                    0.000000e+00
ART_AND_DESIGN         1.243381e+08
AUTO_AND_VEHICLES      5.313021e+07
BEAUTY                 2.719705e+07
BOOKS_AND_REFERENCE    1.921470e+09
BUSINESS               1.001915e+09
COMICS                 5.608615e+07
COMMUNICATION          3.264728e+10
DATING                 2.643108e+08
EDUCATION              8.714520e+08
ENTERTAINMENT          2.869160e+09
EVENTS                 1.597316e+07
FAMILY                 1.025826e+10
FINANCE                8.766487e+08
FOOD_AND_DRINK         2.738988e+08
GAME                   3.508602e+10
HEALTH_AND_FITNESS     1.583073e+09
HOUSE_AND_HOME         1.687125e+08
LIBRARIES_AND_DEMO     6.299591e+07
LIFESTYLE              5.376435e+08
MAPS_AND_NAVIGATION    7.242819e+08
MEDICAL                5.325744e+07
NEWS_AND_MAGAZINES     7.496318e+09
PARENTING              3.152111e+07
PERSONALIZATION        2.325495e+09
PHOTOGRAPHY            1.008825e+10
PRODUCTIVITY           1.417609e+10
SHOPPING               3.247849e+09
SOCIAL                 1.406987e+10
SPORTS                 1.751174e+09
TOOLS                  1.145277e+10
TRAVEL_AND_LOCAL       6.868887e+09
VIDEO_PLAYERS          6.222003e+09
WEATHER                4.261005e+08
Name: Installs, dtype: float64