In [333]:
import pandas as pd

In [334]:
df=pd.read_csv("D:\machine_learning\datasets\studentperformance.csv")

In [335]:
df.isnull()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [336]:
df.isna()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [337]:
df.isna

<bound method DataFrame.isna of      gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
0                      none          72             72             74
1                 completed          69             90             88
2                      none          90             95             93
3                      none          47             57             44
4                      none          76             78             75
..                      ...         ...            ...            ...
995               completed          88             99             95
996                    none          62             55             55
997               completed          59             71             65
998               completed          68             78             77
999                    none          77             86             86

[1000 rows x 8 columns]>

# Day 6

# Aggregate function

1.mean()
2.median()
3.mode()
4.min()
5.max()
6.sum()

In [338]:
data={
    "Age":[22,None,None,30,60],
    "Salary":[None,None,25000,30000,40000]
}
dr=pd.DataFrame(data)

In [339]:
dr

    Age   Salary
0  22.0      NaN
1   NaN      NaN
2   NaN  25000.0
3  30.0  30000.0
4  60.0  40000.0

In [340]:
dr.mean()

Age          37.333333
Salary    31666.666667
dtype: float64

In [341]:
dr.mean(numeric_only=True)

Age          37.333333
Salary    31666.666667
dtype: float64

In [342]:
# Original dataset gives error has it contains the string datatypes

In [343]:
df.mean(numeric_only=True) # Only for numeric data not for string or other datatypes

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [344]:
df.mean(numeric_only=True,axis=0) # gives mean for each column

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [345]:
df.mean(numeric_only=True,axis=1) # for all rows of all columns

0      72.666667
1      82.333333
2      92.666667
3      49.333333
4      76.333333
         ...
995    94.000000
996    57.333333
997    65.000000
998    74.333333
999    83.000000
Length: 1000, dtype: float64

In [346]:
df.mean(numeric_only=True,axis=True) # same as axis=1

0      72.666667
1      82.333333
2      92.666667
3      49.333333
4      76.333333
         ...
995    94.000000
996    57.333333
997    65.000000
998    74.333333
999    83.000000
Length: 1000, dtype: float64

# AGG()
Syntax 1: Gives min,max and other values to all columns df.agg(['func1','func2',...'funcN'])

Syntax 2: Calculate seperate functions for rach columns
df.agg({
    'col_name':'func1',
    'col_name':'func2'
})

In [347]:
df[['reading score','writing score','math score']].agg(['mean','max','min'])

      reading score  writing score  math score
mean         69.169         68.054      66.089
max         100.000        100.000     100.000
min          17.000         10.000       0.000

# Second Syntax

In [348]:
df.agg({
    'writing score':'mean',
    'reading score':'max',
    'math score':'min'
})

writing score     68.054
reading score    100.000
math score         0.000
dtype: float64

In [349]:
df.mode() # It gives most repeated values

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group C,some college,standard,none,65,72,74

In [350]:
df.median(numeric_only=True)

math score       66.0
reading score    70.0
writing score    69.0
dtype: float64

In [351]:
df.sum(numeric_only=True)

math score       66089
reading score    69169
writing score    68054
dtype: int64

In [352]:
df.agg({
    'math score':'mode'
})
# 65 is most repeated in math score

   math score
0          65

In [353]:
df.shape # (1000,8) -> (row_count,column_count) returns in tuple

(1000, 8)

In [354]:
df.count() # Counts all values except [null values]

gender                         1000
race/ethnicity                 1000
parental level of education    1000
lunch                          1000
test preparation course        1000
math score                     1000
reading score                  1000
writing score                  1000
dtype: int64

In [355]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [356]:
data={
    "Age":[22,None,None,30,60],
    "Salary":[None,None,25000,30000,40000]
}
dr=pd.DataFrame(data)

In [357]:
dr.isna

<bound method DataFrame.isna of     Age   Salary
0  22.0      NaN
1   NaN      NaN
2   NaN  25000.0
3  30.0  30000.0
4  60.0  40000.0>

In [358]:
dr.isna().sum() # Gives the number of None values in a column

Age       2
Salary    2
dtype: int64

In [359]:
dr.isnull().sum()

Age       2
Salary    2
dtype: int64

In [360]:
dr.isnull().sum().sum() # It gives sum of None values

np.int64(4)

In [361]:
dr.notnull().sum() # It returns if the values if present

Age       3
Salary    3
dtype: int64

In [362]:
dr.notna()

     Age  Salary
0   True   False
1  False   False
2  False    True
3   True    True
4   True    True

In [363]:
dr[dr['Age'].notna()] # Age column returns only the values which are present

    Age   Salary
0  22.0      NaN
3  30.0  30000.0
4  60.0  40000.0

In [364]:
dr[dr['Salary'].notnull()]

    Age   Salary
2   NaN  25000.0
3  30.0  30000.0
4  60.0  40000.0

# DAY 7

fillna

In [365]:
# Syntax : df.fillna(value) -> returns new df

In [366]:
dr.fillna(0) # It fills 0 inplace of None

    Age   Salary
0  22.0      0.0
1   0.0      0.0
2   0.0  25000.0
3  30.0  30000.0
4  60.0  40000.0

In [367]:
dr

    Age   Salary
0  22.0      NaN
1   NaN      NaN
2   NaN  25000.0
3  30.0  30000.0
4  60.0  40000.0

In [368]:
# df.fillna(value,inplace=True) -> returns new df

# dr.fillna(0,inplace=True) # inplace it fixes the values permanently in dataframe

In [369]:
# Syntax dr.fillna({
    # 'col_name':fill value,
    # 'col_name':fill value
    # })

In [370]:
# dr.fillna({
#     'Age':dr['Age'].mean(),
#     'Salary':df['Salary'].median(),
#     'Experience':df['Experience'].median()
# })

In [371]:
# If inplace is done then comment it and run all
dr

    Age   Salary
0  22.0      NaN
1   NaN      NaN
2   NaN  25000.0
3  30.0  30000.0
4  60.0  40000.0

In [372]:
# df.fillna(method='ffill')

In [373]:
dr.ffill() # Fills null values with above values

    Age   Salary
0  22.0      NaN
1  22.0      NaN
2  22.0  25000.0
3  30.0  30000.0
4  60.0  40000.0

In [374]:
dr.bfill() # Fills null values with below values

    Age   Salary
0  22.0  25000.0
1  30.0  25000.0
2  30.0  25000.0
3  30.0  30000.0
4  60.0  40000.0

# DAY 8

In [375]:
dr.dropna() # If any one column value is missing it removes the entire row

    Age   Salary
3  30.0  30000.0
4  60.0  40000.0

In [376]:
# dr.dropna(inplace=True) # Alter the original values

In [377]:
dr

    Age   Salary
0  22.0      NaN
1   NaN      NaN
2   NaN  25000.0
3  30.0  30000.0
4  60.0  40000.0

In [378]:
dr.dropna(how='all') # Removes the entire row only if all values in row is [null]

    Age   Salary
0  22.0      NaN
2   NaN  25000.0
3  30.0  30000.0
4  60.0  40000.0

In [379]:
dr.dropna(how='any') # Remove entire rows if the column has 1 null value

    Age   Salary
3  30.0  30000.0
4  60.0  40000.0

In [380]:
dr.dropna(subset='Age') # Drops the row in a particular column if they contain Nan values
# Entire column should be Null if it is 1 Null value then it doesnot drop

    Age   Salary
0  22.0      NaN
3  30.0  30000.0
4  60.0  40000.0

In [381]:
dr.dropna(subset=['Salary'])

    Age   Salary
2   NaN  25000.0
3  30.0  30000.0
4  60.0  40000.0

In [382]:
dp=pd.DataFrame({'Gender':['male','female','female',None,'male'],
                 'Age':[None,25,30,None,40],
                 'Salary':[500000,None,25000,None,100000]
                })

In [383]:
dp

   Gender   Age    Salary
0    male   NaN  500000.0
1  female  25.0       NaN
2  female  30.0   25000.0
3    None   NaN       NaN
4    male  40.0  100000.0

In [384]:
dp.dropna(subset=['Gender','Age'],how='all')

   Gender   Age    Salary
0    male   NaN  500000.0
1  female  25.0       NaN
2  female  30.0   25000.0
4    male  40.0  100000.0

In [385]:
dp.dropna(subset=['Gender','Age'],how='any')

   Gender   Age    Salary
1  female  25.0       NaN
2  female  30.0   25000.0
4    male  40.0  100000.0

In [386]:
dp1=pd.DataFrame({'Gender':['male','female','female',None,'male','male'],
                  'Age':[None,30,25,None,40,40],
                  'Salary':[50000,None,25000,None,100000,100000]
                })

In [387]:
dp1

   Gender   Age    Salary
0    male   NaN   50000.0
1  female  30.0       NaN
2  female  25.0   25000.0
3    None   NaN       NaN
4    male  40.0  100000.0
5    male  40.0  100000.0

In [388]:
dp1.drop_duplicates() # Drops the duplicate rows only temporarily

   Gender   Age    Salary
0    male   NaN   50000.0
1  female  30.0       NaN
2  female  25.0   25000.0
3    None   NaN       NaN
4    male  40.0  100000.0

In [389]:
dp1

   Gender   Age    Salary
0    male   NaN   50000.0
1  female  30.0       NaN
2  female  25.0   25000.0
3    None   NaN       NaN
4    male  40.0  100000.0
5    male  40.0  100000.0

In [390]:
# dp1.drop_duplicates(inplace=True)
# If we do inplace=True then it will be permanent

In [391]:
dp1.shape[0] # gives number of rows only

6

In [392]:
upd_dp1=dp1.drop_duplicates() # remove the rows containing duplicates from a particular column

In [393]:
upd_dp1

   Gender   Age    Salary
0    male   NaN   50000.0
1  female  30.0       NaN
2  female  25.0   25000.0
3    None   NaN       NaN
4    male  40.0  100000.0

In [394]:
upd_dp1.shape[0]

5

In [395]:
count_=dp1.shape[0]-upd_dp1.shape[0]
print(count_)

1

In [396]:
dp1[['Age','Salary']].mean(axis=0) #column wise(axis)

Age          33.75
Salary    68750.00
dtype: float64

In [397]:
dp1[['Age','Salary']].mean(axis=1) # row wise(axis)

0    50000.0
1       30.0
2    12512.5
3        NaN
4    50020.0
5    50020.0
dtype: float64

# DAY 8

In [398]:
# drop()

# Syntax dp1.drop(rowindex/colname,axis=0/1,inplace=true/false)

dp1.drop('Age',axis=1) # Removes the entire age column

# dp1.drop('Age',axis=0) # gives error

   Gender    Salary
0    male   50000.0
1  female       NaN
2  female   25000.0
3    None       NaN
4    male  100000.0
5    male  100000.0

In [399]:
dp1.drop(0,axis=0) # drops the 0th index but based on column beacuse 0th index is present in a column therefore axis=1

# 0th index was male

   Gender   Age    Salary
1  female  30.0       NaN
2  female  25.0   25000.0
3    None   NaN       NaN
4    male  40.0  100000.0
5    male  40.0  100000.0

In [400]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [401]:
# df.drop('gender') # KeyError: "['gender'] not found in axis"

# by default axis=0 we need to make it 1 to drop

In [402]:
df.drop('gender',axis=1)

,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,group B,bachelor's degree,standard,none,72,72,74
1,group C,some college,standard,completed,69,90,88
2,group B,master's degree,standard,none,90,95,93
3,group A,associate's degree,free/reduced,none,47,57,44
4,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...
995,group E,master's degree,standard,completed,88,99,95
996,group C,high school,free/reduced,none,62,55,55
997,group C,high school,free/reduced,completed,59,71,65
998,group D,some college,standard,completed,68,78,77
999,group D,some college,free/reduced,none,77,86,86

In [403]:
df.drop(['gender','lunch'],axis=1) # dropping multiple columns

,race/ethnicity,parental level of education,test preparation course,math score,reading score,writing score
0,group B,bachelor's degree,none,72,72,74
1,group C,some college,completed,69,90,88
2,group B,master's degree,none,90,95,93
3,group A,associate's degree,none,47,57,44
4,group C,some college,none,76,78,75
...,...,...,...,...,...,...
995,group E,master's degree,completed,88,99,95
996,group C,high school,none,62,55,55
997,group C,high school,completed,59,71,65
998,group D,some college,completed,68,78,77
999,group D,some college,none,77,86,86

# SYNTAX 2

In [404]:
df.drop([0,1,999,998]) # Multiple rows

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
...,...,...,...,...,...,...,...,...
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65

In [405]:
df.drop(columns=['gender','lunch'])

,race/ethnicity,parental level of education,test preparation course,math score,reading score,writing score
0,group B,bachelor's degree,none,72,72,74
1,group C,some college,completed,69,90,88
2,group B,master's degree,none,90,95,93
3,group A,associate's degree,none,47,57,44
4,group C,some college,none,76,78,75
...,...,...,...,...,...,...
995,group E,master's degree,completed,88,99,95
996,group C,high school,none,62,55,55
997,group C,high school,completed,59,71,65
998,group D,some college,completed,68,78,77
999,group D,some college,none,77,86,86

# groupby() 

It used only for categorical columns, selects the unique values and then stores the indexes of all the values belonging to that group

# retuns in the form of dictionary

Syntax -> df.groupby('col_names')

In [406]:
gr_by=df.groupby('gender') 

# or

# df.groupby('gender').groups

In [407]:
gr_by.groups

{'female': [0, 1, 2, 5, 6, 9, 12, 14, 15, 17, 19, 21, 23, 27, 29, 30, 31, 32, 36, 37, 38, 41, 42, 44, 46, 47, 48, 54, 55, 56, 59, 63, 64, 67, 69, 70, 72, 78, 79, 80, 85, 86, 87, 88, 89, 90, 94, 97, 98, 99, 102, 105, 106, 108, 109, 110, 113, 114, 116, 117, 118, 119, 120, 122, 125, 129, 133, 138, 140, 141, 142, 145, 148, 152, 155, 156, 158, 161, 164, 165, 167, 168, 169, 172, 173, 174, 175, 176, 177, 178, 179, 181, 182, 183, 189, 190, 192, 194, 198, 199, ...], 'male': [3, 4, 7, 8, 10, 11, 13, 16, 18, 20, 22, 24, 25, 26, 28, 33, 34, 35, 39, 40, 43, 45, 49, 50, 51, 52, 53, 57, 58, 60, 61, 62, 65, 66, 68, 71, 73, 74, 75, 76, 77, 81, 82, 83, 84, 91, 92, 93, 95, 96, 100, 101, 103, 104, 107, 111, 112, 115, 121, 123, 124, 126, 127, 128, 130, 131, 132, 134, 135, 136, 137, 139, 143, 144, 146, 147, 149, 150, 151, 153, 154, 157, 159, 160, 162, 163, 166, 170, 171, 180, 184, 185, 186, 187, 188, 191, 193, 195, 196, 197, ...]}

In [408]:
#gr_by.get_group(key) 
# It is used to get specific group, should pass the key as argument, because groups method returns dictionary
gr_by.get_group('male')

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
10,male,group C,associate's degree,standard,none,58,54,52
...,...,...,...,...,...,...,...,...
985,male,group A,high school,standard,none,57,51,54
987,male,group E,some high school,standard,completed,81,75,76
990,male,group E,high school,free/reduced,completed,86,81,75
994,male,group A,high school,standard,none,63,63,62
996,male,group C,high school,free/reduced,none,62,55,55

In [409]:
gr_by.get_group('female')

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
...,...,...,...,...,...,...,...,...
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
995,female,group E,master's degree,standard,completed,88,99,95
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# find the avg of math score in male and female

# 1st method

In [410]:
gr_by.get_group('male').agg({'math score':'mean'})

math score    68.728216
dtype: float64

In [411]:
gr_by.get_group('female').agg({'math score':'mean'})

math score    63.633205
dtype: float64

# 2nd method

In [412]:
avg_math=df.groupby('gender')

In [413]:
avg_math.agg({'math score':'mean'})

        math score
gender
female   63.633205
male     68.728216

# Using Filter Conditions

In [414]:
female=df[df['gender']=='female']
female['math score'].mean()

np.float64(63.633204633204635)

# Using GroupName.agg method

In [415]:
gr_by.agg({'math score':'mean'})

        math score
gender
female   63.633205
male     68.728216

# DAY 9

In [416]:
# To get Multiple Aggregate of Multiple groups attribute

groups=df.groupby('gender')
groups.agg({'math score':['mean','sum']})

       math score
             mean    sum
gender
female  63.633205  32962
male    68.728216  33127

In [417]:
groups.agg({'writing score':['mean','median'],'reading score':['mean','sum']})

       writing score        reading score
                mean median          mean    sum
gender
female     72.467181   74.0     72.608108  37611
male       63.311203   64.0     65.473029  31558

In [418]:
df[['reading score','writing score','math score']].sum() # Default axis=0

reading score    69169
writing score    68054
math score       66089
dtype: int64

In [419]:
add=df[['writing score','reading score','math score']].sum(axis=1)
add

0      218
1      247
2      278
3      148
4      229
      ...
995    282
996    172
997    195
998    223
999    249
Length: 1000, dtype: int64

In [420]:
df['Total score']=add # Adding new column to the dataframe

# df['col name'] = var

In [421]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total score
0,female,group B,bachelor's degree,standard,none,72,72,74,218
1,female,group C,some college,standard,completed,69,90,88,247
2,female,group B,master's degree,standard,none,90,95,93,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,148
4,male,group C,some college,standard,none,76,78,75,229

In [422]:
# rename()

# Syntax -> df.rename(columns={'oldname':'newname'})

In [423]:
df.rename(columns={'Total score':'Final score'})
# Doesnot change the column name permanently

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Final score
0,female,group B,bachelor's degree,standard,none,72,72,74,218
1,female,group C,some college,standard,completed,69,90,88,247
2,female,group B,master's degree,standard,none,90,95,93,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,148
4,male,group C,some college,standard,none,76,78,75,229
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,282
996,male,group C,high school,free/reduced,none,62,55,55,172
997,female,group C,high school,free/reduced,completed,59,71,65,195
998,female,group D,some college,standard,completed,68,78,77,223
999,female,group D,some college,free/reduced,none,77,86,86,249

In [424]:
df
# Now the column name is again changes to Total score

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total score
0,female,group B,bachelor's degree,standard,none,72,72,74,218
1,female,group C,some college,standard,completed,69,90,88,247
2,female,group B,master's degree,standard,none,90,95,93,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,148
4,male,group C,some college,standard,none,76,78,75,229
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,282
996,male,group C,high school,free/reduced,none,62,55,55,172
997,female,group C,high school,free/reduced,completed,59,71,65,195
998,female,group D,some college,standard,completed,68,78,77,223
999,female,group D,some college,free/reduced,none,77,86,86,249

In [425]:
df.rename(columns={'Total score':' Final score'},inplace=True)
# By doing inplace=True the column is renamed permanently
# or

# df=df.rename(columns={'Total score':'Final score'})

In [426]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Final score
0,female,group B,bachelor's degree,standard,none,72,72,74,218
1,female,group C,some college,standard,completed,69,90,88,247
2,female,group B,master's degree,standard,none,90,95,93,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,148
4,male,group C,some college,standard,none,76,78,75,229

In [427]:
# Can also change the index value
df.rename(index={0:'A',1:'B'})

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Final score
A,female,group B,bachelor's degree,standard,none,72,72,74,218
B,female,group C,some college,standard,completed,69,90,88,247
2,female,group B,master's degree,standard,none,90,95,93,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,148
4,male,group C,some college,standard,none,76,78,75,229
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,282
996,male,group C,high school,free/reduced,none,62,55,55,172
997,female,group C,high school,free/reduced,completed,59,71,65,195
998,female,group D,some college,standard,completed,68,78,77,223
999,female,group D,some college,free/reduced,none,77,86,86,249

# MAP() and REPLACE ()

In [428]:
# map() and replace() are used to replace the values

# map is used to only replace value from a specific column

# replace is used to replace values in an entire dataframe

# syntax -> df["colname"].map({'oldvalue':'newvalue'}

# syntax -> df.replace({'oldvalue':'newvalue'})
# df['colname'].replace({'old value':'new value'})

In [429]:

df['gender'].map({'female':'F'})
# replaces only the mentioned value and keeps other value as NaN

0        F
1        F
2        F
3      NaN
4      NaN
      ...
995      F
996    NaN
997      F
998      F
999      F
Name: gender, Length: 1000, dtype: object

In [430]:
df['gender'].map({'female':'F','male':'M'})

0      F
1      F
2      F
3      M
4      M
      ..
995    F
996    M
997    F
998    F
999    F
Name: gender, Length: 1000, dtype: object

In [431]:
df['gender'].replace({'female':'F'})
# replaces female name as F and male as male

0         F
1         F
2         F
3      male
4      male
       ...
995       F
996    male
997       F
998       F
999       F
Name: gender, Length: 1000, dtype: object

In [432]:
df.replace({'female':'F'})

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Final score
0,F,group B,bachelor's degree,standard,none,72,72,74,218
1,F,group C,some college,standard,completed,69,90,88,247
2,F,group B,master's degree,standard,none,90,95,93,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,148
4,male,group C,some college,standard,none,76,78,75,229
...,...,...,...,...,...,...,...,...,...
995,F,group E,master's degree,standard,completed,88,99,95,282
996,male,group C,high school,free/reduced,none,62,55,55,172
997,F,group C,high school,free/reduced,completed,59,71,65,195
998,F,group D,some college,standard,completed,68,78,77,223
999,F,group D,some college,free/reduced,none,77,86,86,249

# DAY 10

In [436]:
# sort_values() this will also change the index based on sort

# syntax -> df.sort_values(colname)

# df.sort_values('Final score',ascending=False)

In [438]:
# df.sort_values('Final score',ignore_index=True) 
# arranges index in order and values as sorted

In [440]:
# df.sort_values(['Final score','math score']
# it first sorts the first column but if the values of the first column are same then it will go for its corresponding 2nd column value and then sorts based on that