In [120]:
import pandas as pd

In [121]:
df=pd.read_csv("D:\machine_learning\datasets\studentperformance.csv")

In [122]:
df.isnull()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [123]:
df.isna()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [124]:
df.isna

<bound method DataFrame.isna of      gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
0                      none          72             72             74
1                 completed          69             90             88
2                      none          90             95             93
3                      none          47             57             44
4                      none          76             78             75
..                      ...         ...            ...            ...
995               completed          88             99             95
996                    none          62             55             55
997               completed          59             71             65
998               completed          68             78             77
999                    none          77             86             86

[1000 rows x 8 columns]>

# Day 6

# Aggregate function

1.mean()
2.median()
3.mode()
4.min()
5.max()
6.sum()

In [125]:
data={
    "Age":[22,None,None,30,60],
    "Salary":[None,None,25000,30000,40000]
}
dr=pd.DataFrame(data)

In [126]:
dr

    Age   Salary
0  22.0      NaN
1   NaN      NaN
2   NaN  25000.0
3  30.0  30000.0
4  60.0  40000.0

In [127]:
dr.mean()

Age          37.333333
Salary    31666.666667
dtype: float64

In [128]:
dr.mean(numeric_only=True)

Age          37.333333
Salary    31666.666667
dtype: float64

In [129]:
# Original dataset gives error has it contains the string datatypes

In [130]:
df.mean(numeric_only=True) # Only for numeric data not for string or other datatypes

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [131]:
df.mean(numeric_only=True,axis=0) # gives mean for each column

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [132]:
df.mean(numeric_only=True,axis=1) # for all rows of all columns

0      72.666667
1      82.333333
2      92.666667
3      49.333333
4      76.333333
         ...
995    94.000000
996    57.333333
997    65.000000
998    74.333333
999    83.000000
Length: 1000, dtype: float64

In [133]:
df.mean(numeric_only=True,axis=True) # same as axis=1

0      72.666667
1      82.333333
2      92.666667
3      49.333333
4      76.333333
         ...
995    94.000000
996    57.333333
997    65.000000
998    74.333333
999    83.000000
Length: 1000, dtype: float64

# AGG()
Syntax 1: Gives min,max and other values to all columns df.agg(['func1','func2',...'funcN'])

Syntax 2: Calculate seperate functions for rach columns
df.agg({
    'col_name':'func1',
    'col_name':'func2'
})

In [134]:
df[['reading score','writing score','math score']].agg(['mean','max','min'])

      reading score  writing score  math score
mean         69.169         68.054      66.089
max         100.000        100.000     100.000
min          17.000         10.000       0.000

# Second Syntax

In [135]:
df.agg({
    'writing score':'mean',
    'reading score':'max',
    'math score':'min'
})

writing score     68.054
reading score    100.000
math score         0.000
dtype: float64

In [136]:
df.mode() # It gives most repeated values

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group C,some college,standard,none,65,72,74

In [137]:
df.median(numeric_only=True)

math score       66.0
reading score    70.0
writing score    69.0
dtype: float64

In [138]:
df.sum(numeric_only=True)

math score       66089
reading score    69169
writing score    68054
dtype: int64

In [139]:
df.agg({
    'math score':'mode'
})
# 65 is most repeated in math score

   math score
0          65

In [140]:
df.shape # (1000,8) -> (row_count,column_count) returns in tuple

(1000, 8)

In [141]:
df.count() # Counts all values except [null values]

gender                         1000
race/ethnicity                 1000
parental level of education    1000
lunch                          1000
test preparation course        1000
math score                     1000
reading score                  1000
writing score                  1000
dtype: int64

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [143]:
data={
    "Age":[22,None,None,30,60],
    "Salary":[None,None,25000,30000,40000]
}
dr=pd.DataFrame(data)

In [144]:
dr.isna

<bound method DataFrame.isna of     Age   Salary
0  22.0      NaN
1   NaN      NaN
2   NaN  25000.0
3  30.0  30000.0
4  60.0  40000.0>

In [145]:
dr.isna().sum() # Gives the number of None values in a column

Age       2
Salary    2
dtype: int64

In [146]:
dr.isnull().sum()

Age       2
Salary    2
dtype: int64

In [147]:
dr.isnull().sum().sum() # It gives sum of None values

np.int64(4)

In [148]:
dr.notnull().sum() # It returns if the values if present

Age       3
Salary    3
dtype: int64

In [149]:
dr.notna()

     Age  Salary
0   True   False
1  False   False
2  False    True
3   True    True
4   True    True

In [150]:
dr[dr['Age'].notna()] # Age column returns only the values which are present

    Age   Salary
0  22.0      NaN
3  30.0  30000.0
4  60.0  40000.0

In [151]:
dr[dr['Salary'].notnull()]

    Age   Salary
2   NaN  25000.0
3  30.0  30000.0
4  60.0  40000.0

# DAY 7

fillna

In [152]:
# Syntax : df.fillna(value) -> returns new df

In [153]:
dr.fillna(0) # It fills 0 inplace of None

    Age   Salary
0  22.0      0.0
1   0.0      0.0
2   0.0  25000.0
3  30.0  30000.0
4  60.0  40000.0

In [154]:
dr

    Age   Salary
0  22.0      NaN
1   NaN      NaN
2   NaN  25000.0
3  30.0  30000.0
4  60.0  40000.0

In [155]:
# df.fillna(value,inplace=True) -> returns new df

# dr.fillna(0,inplace=True) # inplace it fixes the values permanently in dataframe

In [156]:
# Syntax dr.fillna({
    # 'col_name':fill value,
    # 'col_name':fill value
    # })

In [157]:
# dr.fillna({
#     'Age':dr['Age'].mean(),
#     'Salary':df['Salary'].median(),
#     'Experience':df['Experience'].median()
# })

In [158]:
# If inplace is done then comment it and run all
dr

    Age   Salary
0  22.0      NaN
1   NaN      NaN
2   NaN  25000.0
3  30.0  30000.0
4  60.0  40000.0

In [159]:
# df.fillna(method='ffill')

In [160]:
dr.ffill() # Fills null values with above values

    Age   Salary
0  22.0      NaN
1  22.0      NaN
2  22.0  25000.0
3  30.0  30000.0
4  60.0  40000.0

In [161]:
dr.bfill() # Fills null values with below values

    Age   Salary
0  22.0  25000.0
1  30.0  25000.0
2  30.0  25000.0
3  30.0  30000.0
4  60.0  40000.0

# DAY 8

In [162]:
dr.dropna() # If any one column value is missing it removes the entire row

    Age   Salary
3  30.0  30000.0
4  60.0  40000.0

In [163]:
# dr.dropna(inplace=True) # Alter the original values

In [164]:
dr

    Age   Salary
0  22.0      NaN
1   NaN      NaN
2   NaN  25000.0
3  30.0  30000.0
4  60.0  40000.0

In [165]:
dr.dropna(how='all') # Removes the entire row only if all values in row is [null]

    Age   Salary
0  22.0      NaN
2   NaN  25000.0
3  30.0  30000.0
4  60.0  40000.0

In [167]:
dr.dropna(how='any') # Remove entire rows if the column has 1 null value

    Age   Salary
3  30.0  30000.0
4  60.0  40000.0

In [170]:
dr.dropna(subset='Age') # Drops the row in a particular column if they contain Nan values
# Entire column should be Null if it is 1 Null value then it doesnot drop

    Age   Salary
0  22.0      NaN
3  30.0  30000.0
4  60.0  40000.0

In [171]:
dr.dropna(subset=['Salary'])

    Age   Salary
2   NaN  25000.0
3  30.0  30000.0
4  60.0  40000.0

In [172]:
dp=pd.DataFrame({'Gender':['male','female','female',None,'male'],
                 'Age':[None,25,30,None,40],
                 'Salary':[500000,None,25000,None,100000]
                })

In [173]:
dp

   Gender   Age    Salary
0    male   NaN  500000.0
1  female  25.0       NaN
2  female  30.0   25000.0
3    None   NaN       NaN
4    male  40.0  100000.0

In [174]:
dp.dropna(subset=['Gender','Age'],how='all')

   Gender   Age    Salary
0    male   NaN  500000.0
1  female  25.0       NaN
2  female  30.0   25000.0
4    male  40.0  100000.0

In [176]:
dp.dropna(subset=['Gender','Age'],how='any')

   Gender   Age    Salary
1  female  25.0       NaN
2  female  30.0   25000.0
4    male  40.0  100000.0

In [177]:
dp1=pd.DataFrame({'Gender':['male','female','female',None,'male','male'],
                  'Age':[None,30,25,None,40,40],
                  'Salary':[50000,None,25000,None,100000,100000]
                })

In [178]:
dp1

   Gender   Age    Salary
0    male   NaN   50000.0
1  female  30.0       NaN
2  female  25.0   25000.0
3    None   NaN       NaN
4    male  40.0  100000.0
5    male  40.0  100000.0

In [179]:
dp1.drop_duplicates() # Drops the duplicate rows only temporarily

   Gender   Age    Salary
0    male   NaN   50000.0
1  female  30.0       NaN
2  female  25.0   25000.0
3    None   NaN       NaN
4    male  40.0  100000.0

In [180]:
dp1

   Gender   Age    Salary
0    male   NaN   50000.0
1  female  30.0       NaN
2  female  25.0   25000.0
3    None   NaN       NaN
4    male  40.0  100000.0
5    male  40.0  100000.0

In [182]:
# dp1.drop_duplicates(inplace=True)
# If we do inplace=True then it will be permanent

In [183]:
dp1.shape[0] # gives number of rows only

6

In [184]:
upd_dp1=dp1.drop_duplicates() # remove the rows containing duplicates from a particular column

In [185]:
upd_dp1

   Gender   Age    Salary
0    male   NaN   50000.0
1  female  30.0       NaN
2  female  25.0   25000.0
3    None   NaN       NaN
4    male  40.0  100000.0

In [186]:
upd_dp1.shape[0]

5

In [187]:
count_=dp1.shape[0]-upd_dp1.shape[0]
print(count_)

1

In [189]:
dp1[['Age','Salary']].mean(axis=0) #column wise(axis)

Age          33.75
Salary    68750.00
dtype: float64

In [190]:
dp1[['Age','Salary']].mean(axis=1) # row wise(axis)

0    50000.0
1       30.0
2    12512.5
3        NaN
4    50020.0
5    50020.0
dtype: float64

12-3-26